[package]
name = "thesaurus-web-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nanoserde = "0.1.29"
ureq = "2.2.0"
urlencoding = "2.1.0"
# serde = "1.0.130"
