[package]
name = "thesaurus-web-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] } 
urlencoding = "2.1.0"
ureq = "2.4.0"
serde_json = "1.0.81"
